 dat<-read.table(file="out.dat")
 sim<-read.table(file="lattice2d_0_r1_1.csv",sep=" ",header=F)
postscript(file="comparisoni2d.ps",paper="letter")
plot(dat[,1],dat[,4],type="l",xlab="Time Units",ylab="C_n",lwd=1,ylim=c(0,600))
box(lwd=3)
 points(sim[,1],sim[,10],type="l",col=2,lwd=1)
  points(sim[,1],(sim[,10]-sqrt(sim[,21])),type="l",col=3,lwd=1)
   points(sim[,1],(sim[,10]+sqrt(sim[,21])),type="l",col=3,lwd=1)
 legend(6000,300,legend=c("Mass Action","Simulated","Standard Dev."),lty=1,col=c(1,2,3),lwd=3)
#     title("Comparison of Mass Action and Simulated Data\nNo Crowding")
     axis(lwd=1,side=c(1))
     axis(lwd=1,side=c(2))
dev.off()

