dat3d<-read.table(file="3dfits",sep=" ",header=T,row.names=NULL)
#dat2d<-read.table(file="2dfits",sep=" ",header=T,row.names=NULL)
load("accVol.dat")
fdat<-read.table(file="fractal_dim.dat",header=T)
names(fdat)<-c("radius","pct","fd")
names(dat3d)[2]<-"radius"
names(dat3d)[3]<-"pct"
all<-merge(dat3d,accVol,by=c("radius","pct"),all=T)
all<-merge(all,fdat,by=c("radius","pct"),all=T)
sv<-all[all$Model=="SV/MA",]
sv<-sv[!is.na(sv$fd),]
st<-all[all$Model=="ST/MA",]
st<-st[!is.na(st$fd),]
ma<-all[all$Model=="MA/MA",]
ma<-ma[!is.na(ma$fd),]
ms<-all[all$Model=="ST/ST",]
ms<-ms[!is.na(ms$fd),]
st<-st[!(st$radius==1 & st$pct==75),]

#### Correlations with fd ######
jpeg(file="fd_cor_k1.jpeg",quality=100)
par(mfrow=c(2,2))
o<-order(sv$fd)
plot(sv$fd[o],sv$k1[o],typ="b")
o<-order(st$fd)
plot(st$fd[o],st$k1[o],typ="b")
o<-order(ma$fd)
plot(ma$fd[o],ma$k1[o],typ="b")
o<-order(ms$fd)
plot(ms$fd[o],ms$k1[o],typ="b")
dev.off()
jpeg(file="fd_cor_k2.jpeg",quality=100)
par(mfrow=c(2,2))
o<-order(sv$fd)
plot(sv$fd[o],sv$k2[o],typ="b",col=sv$radius[o])
o<-order(st$fd)
plot(st$fd[o],st$k2[o],typ="b")
o<-order(ma$fd)
plot(ma$fd[o],ma$k2[o],typ="b")
o<-order(ms$fd)
plot(ms$fd[o],ms$k2[o],typ="b",col=ms$radius[o])

dev.off()
jpeg(file="fd_cor_tau_eta.jpeg",quality=100)
par(mfrow=c(2,2))
o<-order(sv$fd)
plot(sv$fd[o],sv$tau_eta[o],typ="b",col=sv$radius[o])
o<-order(st$fd)
plot(st$fd[o],st$tau_eta[o],typ="b")
#o<-order(ma$fd)
#plot(ma$fd[o],ma$k2[o],typ="b")
o<-order(ms$fd)
plot(ms$fd[o],ms$tau_eta[o],typ="b",col=ms$radius[o])


dev.off()
jpeg(file="fd_cor_h_zeta.jpeg",quality=100)
par(mfrow=c(2,2))
o<-order(sv$fd)
plot(sv$fd[o],sv$h_zeta[o],typ="b",col=sv$radius[o])
o<-order(st$fd)
plot(st$fd[o],st$h_zeta[o],typ="b")
#o<-order(ma$fd)
#plot(ma$fd[o],ma$k2[o],typ="b")
o<-order(ms$fd)
plot(ms$fd[o],ms$h_zeta[o],typ="b",col=ms$radius[o])
dev.off()
jpeg(file="pct_cor_k1.jpeg",quality=100)
#### Correlations with pct.1 ######
par(mfrow=c(2,2))
o<-order(sv$pct.1)
plot(sv$pct.1[o],sv$k1[o],typ="b")
o<-order(st$pct.1)
plot(st$pct.1[o],st$k1[o],typ="b")
o<-order(ma$pct.1)
plot(ma$pct.1[o],ma$k1[o],typ="b")
o<-order(ms$pct.1)
plot(ms$pct.1[o],ms$k1[o],typ="b")

dev.off()
jpeg(file="pct_cor_k2.jpeg",quality=100)

par(mfrow=c(2,2))
o<-order(sv$pct.1)
plot(sv$pct.1[o],sv$k2[o],typ="b",col=sv$radius[o])
o<-order(st$pct.1)
plot(st$pct.1[o],st$k2[o],typ="b")
o<-order(ma$pct.1)
plot(ma$pct.1[o],ma$k2[o],typ="b")
o<-order(ms$pct.1)
plot(ms$pct.1[o],ms$k2[o],typ="b",col=ms$radius[o])

dev.off()
jpeg(file="pct_cor_tau_eta.jpeg",quality=100)

par(mfrow=c(2,2))
o<-order(sv$pct.1)
plot(sv$pct.1[o],sv$tau_eta[o],typ="b",col=sv$radius[o])
o<-order(st$pct.1)
plot(st$pct.1[o],st$tau_eta[o],typ="b")
#o<-order(ma$pct.1)
#plot(ma$pct.1[o],ma$k2[o],typ="b")
o<-order(ms$pct.1)
plot(ms$pct.1[o],ms$tau_eta[o],typ="b",col=ms$radius[o])

dev.off()
jpeg(file="pct_cor_h_zeta.jpeg",quality=100)
par(mfrow=c(2,2))
o<-order(sv$pct.1)
plot(sv$pct.1[o],sv$h_zeta[o],typ="b",col=sv$radius[o])
o<-order(st$pct.1)
plot(st$pct.1[o],st$h_zeta[o],typ="b")
#o<-order(ma$pct.1)
#plot(ma$pct.1[o],ma$k2[o],typ="b")
o<-order(ms$pct.1)
plot(ms$pct.1[o],ms$h_zeta[o],typ="b",col=ms$radius[o])
dev.off()
jpeg(file="volume_cor_k1.jpeg",quality=100)
#### Correlations with volume ########
par(mfrow=c(2,2))
o<-order(sv$pct_vol)
plot(sv$pct_vol[o],sv$k1[o],typ="b")
o<-order(st$pct_vol)
plot(st$pct_vol[o],st$k1[o],typ="b")
o<-order(ma$pct_vol)
plot(ma$pct_vol[o],ma$k1[o],typ="b")
o<-order(ms$pct_vol)
plot(ms$pct_vol[o],ms$k1[o],typ="b")

dev.off()
jpeg(file="volume_cor_k2.jpeg",quality=100)
par(mfrow=c(2,2))
o<-order(sv$pct_vol)
plot(sv$pct_vol[o],sv$k2[o],typ="b",col=sv$radius[o])
o<-order(st$pct_vol)
plot(st$pct_vol[o],st$k2[o],typ="b")
o<-order(ma$pct_vol)
plot(ma$pct_vol[o],ma$k2[o],typ="b")
o<-order(ms$pct_vol)
plot(ms$pct_vol[o],ms$k2[o],typ="b",col=ms$radius[o])
dev.off()
jpeg(file="volume_cor_tau_eta.jpeg",quality=100)
par(mfrow=c(2,2))
o<-order(sv$pct_vol)
plot(sv$pct_vol[o],sv$tau_eta[o],typ="b",col=sv$radius[o])
o<-order(st$pct_vol)
plot(st$pct_vol[o],st$tau_eta[o],typ="b")
#o<-order(ma$pct_vol)
#plot(ma$pct_vol[o],ma$k2[o],typ="b")
o<-order(ms$pct_vol)
plot(ms$pct_vol[o],ms$tau_eta[o],typ="b",col=ms$radius[o])
dev.off()
jpeg(file="volume_cor_h_zeta.jpeg",quality=100)
par(mfrow=c(2,2))
o<-order(sv$pct_vol)
plot(sv$pct_vol[o],sv$h_zeta[o],typ="b",col=sv$radius[o])
o<-order(st$pct_vol)
plot(st$pct_vol[o],st$h_zeta[o],typ="b")
#o<-order(ma$pct_vol)
#plot(ma$pct_vol[o],ma$k2[o],typ="b")
o<-order(ms$pct_vol)
plot(ms$pct_vol[o],ms$h_zeta[o],typ="b",col=ms$radius[o])
dev.off()
